this is python tutorial

This is our first program in pyhton. All the best!

In [1]:
print("Heello World!")

Heello World!

 $ a = b + c $

In [48]:
x=2

In [49]:
y=5

In [50]:
print(x+y)

7

In [51]:
del x

In [8]:
print(x)

NameError: name 'x' is not defined

In [9]:
print(type(y))

<class 'int'>

In [10]:
x=3

In [11]:
%whos

Variable   Type    Data/Info
----------------------------
x          int     3
y          int     5

In [14]:
print(type(x))

<class 'int'>

In [15]:
x=5.7

In [16]:
%whos

Variable   Type     Data/Info
-----------------------------
x          float    5.7
y          int      5

In [17]:
print(type(x))

<class 'float'>

In [18]:
abcd=556.32

In [19]:
%whos

Variable   Type     Data/Info
-----------------------------
abcd       float    556.32
x          float    5.7
y          int      5

In [20]:
a,b,c,d,f=3,5,6.0,7.2, -3

In [21]:
%whos

Variable   Type     Data/Info
-----------------------------
a          int      3
abcd       float    556.32
b          int      5
c          float    6.0
d          float    7.2
f          int      -3
x          float    5.7
y          int      5

In [22]:
del abcd

In [23]:
%whos

Variable   Type     Data/Info
-----------------------------
a          int      3
b          int      5
c          float    6.0
d          float    7.2
f          int      -3
x          float    5.7
y          int      5

In [24]:
print(abcd)

NameError: name 'abcd' is not defined

In [25]:
c=2+4j

In [26]:
print(type(c))

<class 'complex'>

In [3]:
s = "hello, how are you"

SyntaxError: invalid syntax (953547725.py, line 1)

In [28]:
print(type(s))

<class 'str'>

# operators

In [29]:
%whos

Variable   Type       Data/Info
-------------------------------
a          int        3
b          int        5
c          complex    (2+4j)
d          float      7.2
f          int        -3
s          str        hello, how are you
x          float      5.7
y          int        5

In [33]:
sum_AandB = a+b

In [34]:
print(sum_AandB)

8

In [35]:
print(type(sum_AandB))

<class 'int'>

In [36]:
type(a+d)

float

In [37]:
v=((a+d)**3)/4

In [38]:
print(v)

265.30199999999996

In [39]:
s1="hello"

In [40]:
s2="world"

In [41]:
print(s1+s2)

helloworld

In [43]:
3x = 2

SyntaxError: invalid decimal literal (62377335.py, line 1)

# Bool

In [46]:
a = True
b = True
c = False

In [47]:
%whos

Variable    Type     Data/Info
------------------------------
a           bool     True
b           bool     True
c           bool     False
d           float    7.2
f           int      -3
s           str      hello, how are you
s1          str      hello
s2          str      world
sum_AandB   int      8
v           float    265.30199999999996
x           float    5.7
y           int      5

In [48]:
print(a and b)
print(a and c)
print(c and a)

True
False
False

In [49]:
d = a or c
print (d)

True

In [50]:
not(a)

False

In [51]:
not(b)

False

In [52]:
not(c)

True

In [54]:
t = not(d)

In [55]:
type(t)

bool

In [56]:
print(t)

False

In [57]:
not((a and b) or (c or d))

False

# Comparisons

In [58]:
print(2<3)

True

In [59]:
c= 2<3

In [63]:
print(type(c))
print(c)

<class 'bool'>
True

In [64]:
d = 3==4

In [65]:
print(d)

False

In [29]:
X = 3==3.0

In [30]:
print(type(X))

<class 'bool'>

In [70]:
x = 4
y = 9
z = 8.3
r = -3

In [74]:
x<y and z<y or r==x

True

In [75]:
x<y and  r==x or z<y

True

In [76]:
print(round(4.655555346837, 3))

4.656

In [80]:
G= divmod(43, 5)

In [81]:
print(type(G))

<class 'tuple'>

In [82]:
print(G)

(8, 3)

In [83]:
G[0]

8

In [84]:
43//5

8

In [85]:
43%5

3

In [32]:
print(isinstance(1, int))
print(isinstance(1.0, int))
print(isinstance(1.0, (int, float)))

True
False
True

In [90]:
isinstance(2+3j,(int, float, str, complex))

True

In [91]:
2**4

16

In [92]:
pow(2,4)

16

In [33]:
pow(2,4,7)

2

In [35]:
input("enter a value")

enter a value 45

'45'

In [97]:
a=input("enter a value")

enter a value 45

In [36]:
type(a)

int

In [99]:
a= int(a)

In [100]:
type(a)

int

In [102]:
print(a-34)

11

In [103]:
a=float( input("enter a real no: "))

enter a real no:  55

In [104]:
type(a)

float

In [106]:
b=float(input("enter a real number:"))

enter a real number: abc

ValueError: could not convert string to float: 'abc'

In [107]:
pow?

Signature: pow(base, exp, mod=None)
Docstring:
Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments

Some types, such as ints, are able to use a more efficient algorithm when
invoked using the three argument form.
Type:      builtin_function_or_method

In [110]:
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments

    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.

In [112]:
a=int(input())

 56

In [115]:
b=int(input())

 59

In [121]:
if a>b:
    print(a)
    print("I am still inside the if condition")
print("I am outside of the if condition")

I am outside of the if condition

In [122]:
if a>b:
    print(a)
if b>a:
    print(b)

59
I am outside of the if condition

In [123]:
if a>b:
    print("a is greater than b")
else:
    print("a is not greater than b")

a is not greater than b

In [128]:
a = int(input())
b = int(input())
if a>b:
    print("a is greater than b")
else:
    print("a is not greater than b")

 45
 45

a is not greater than b

In [129]:
a = int(input())
b = int(input())
if a>b:
    print("a is greater than b")
elif a==b:
    print("a is equal to b")
else: 
    print("b is greater than a")

 10
 10

a is equal to b

In [132]:
a = 1
b = 5
if a==b:
    print("equal")
elif a>b:
    print("A")
else:
    print("B")
print("not in if")

B
not in if

In [134]:
a = 9
b = 10
print("A") if a>b else print("=") if a==b else print("B")

B

In [6]:
import pandas as pd

In [7]:
import numpy as ny

## *this is a markdown in italics*

**

In [1]:
B=a+b

NameError: name 'a' is not defined

In [2]:
a= 5

In [4]:
b = 7

In [5]:
B = a + b

In [6]:
print(B)

12

In [8]:
C = b-a

In [9]:
print(C)

2

In [16]:
D = b**a

In [17]:
print(D)

16807

In [20]:
A = (b+c)**3/4

In [19]:
c= 4

In [22]:
print(A)

332.75

In [25]:
print(_)

In [4]:
A = 5

In [5]:
print(A)

5

In [6]:
print(A)

5

In [15]:
len(A)

NameError: name 'A' is not defined

In [20]:
x = float(input("enter a number"))
y= round(x)
if y>x: 
    Integerportion = y-1
    print(Integerportion)
else:
    Integerportion= y
    print(y)    
if Integerportion%2==0:
    print ("even")
else: print("odd")

enter a number 44

44
even

In [29]:
n = float(input("enter a number"))
i = 1      
while i<n:
    print (i)
    i= i + 1
    print("this is iteration number:", i)
else :
    print("end")

enter a number 7

1
this is iteration number: 2
2
this is iteration number: 3
3
this is iteration number: 4
4
this is iteration number: 5
5
this is iteration number: 6
6
this is iteration number: 7
end

In [ ]:
n = float(input("enter a number"))
i = 1      
while i<n:
    if i%2 == 0:
        print (i)
        i= i + 1
    print("this is iteration number:", i)
   break
else :
    print("end")

In [3]:
n = float(input("enter a number"))
i = 1      
while i<n:
       print (i**2)
       print("this is iteration number:", i)
       i = i+1
print("end")

enter a number 9

1
this is iteration number: 1
4
this is iteration number: 2
9
this is iteration number: 3
16
this is iteration number: 4
25
this is iteration number: 5
36
this is iteration number: 6
49
this is iteration number: 7
64
this is iteration number: 8
end

In [1]:
n = int(input("enter a number"))
i = 1
while i<n:
    if i%2==0:
        print (i)
    else:
        pass
    i = i+1
print("done")

enter a number 5

2
4
done

In [1]:
n = 10
i = 1
while True:
    if i%2==0:
        break
    else:
        print ("inside else")
        i = i+1
print("done")

inside else
done

In [ ]:
n = 10
i = 1
while True:
    if i%2 !=0:
       i = i+1
       continue
        print ("inside if")
        break
print("done")

In [28]:
#Python as a calculator
2 + 3
3 - 2
10 * 5
10 / 5
2 ** 3
10 % 3

1

In [37]:
#Variables
50000
#Instead of repeatedly writing, we give it a name 
income = 50000
# income now produces the value of 50000
income
#performing calculations
income_new=income*12
#creating several variables
age = 25
education = 16
income = 50000

In [39]:
#comments are notes for humans, python ignores everything after #
#Data types:Integerr,Float, string, boolean
age = 25
income = 50000.50
name = "Neha"
employed = True
#asking the type of dat/variable
type(age)
type(education)
type(name)
type(employed)

bool

In [52]:
#Python Lists- collection of values, pyhton starts counting from zero

#Creating lists
ages = [21, 22, 23, 24, 25]
income = [25000, 30000, 35000, 40000, 45000]
cities = ["Delhi", "Mumbai", "Hyderabad", "Chennai"]
student = ["Neha", 25, 50000, True]

#Indexing
cities = ["Delhi", "Mumbai", "Hyderabad", "Chennai"]
cities[0]
cities[1]
#negative indexing
cities[-1]
cities[-2]

#slicing: taking a portion of a list [start : stop]; The start position is included.The stop position is not included.
cities[0:2]
cities[0:3]
#first two
cities[:2]
#From position 2 to the end
cities[2:]
#entire list
cities[:]
#specifying a step- this takes every second item
cities[::2]

['Delhi', 'Hyderabad']

In [69]:
#some of the important functions
income = [25000, 30000, 35000, 40000]
#length
len(income)
max(income)
min(income)
sum(income)
sorted(income)

[25000, 30000, 35000, 40000]

In [48]:
#adding values
income.append(45000)

In [44]:
income

[20000, 20000, 25000, 30000, 35000, 40000, 45000, 45000]

In [49]:
#Insert at a particular position: check
income.insert(3, 50000)

In [50]:
income

[20000,
 20000,
 25000,
 50000,
 50000,
 50000,
 30000,
 35000,
 40000,
 45000,
 45000,
 45000,
 45000,
 45000,
 45000]

In [ ]:
#removing values
income.remove(20000)
#removes the last item
income.pop()
#removing by index
income.pop(0)

In [ ]:
#iteration-going through items one by one
cities = ["Delhi", "Mumbai", "Hyderabad", "Chennai"]

for city in cities:
    print(city)

In [ ]:
#Dictionaries- it stores KEY → VALUE
student = {
    "name": "Neha",
    "age": 25,
    "education": 16,
    "income": 50000
}
#accessing dictionary values
student["name"]
student["income"]
#accessing dictionary keys & Values
student.keys()
student.values()
#accesing keys and values
student.items()
for key, value in student.items():
    print(key, value)
#adding a dictionary item
student["gender"] = "Female"
#nested dictionaries
students = {
    "student1": {
        "name": "A",
        "age": 20,
        "income": 30000
    },
    "student2": {
        "name": "B",
        "age": 21,
        "income": 35000
    }
}
#accessing 
students["student1"]["income"]

pyhton Libraries: Numpy (Numerical calculations, arrays, matrices), Pandas(Data handling, cleaning, tables), Matplotlib(Graphs and visualization), Seaborn(Statistical visualizations), scikit-learn(Prediction, classification, ML), statsmodels(Regression, hypothesis tests, time series)
Libraries have sample datasets
Step 1 Load Pandas
Step 2 — Load Statsmodels
Step 3 — Read your dataset
Step 4 — Examine the data
Step 5: Analysis

Purpose:

Read CSV/Excel files
Clean data
Filter data
Group data

In [ ]:
#Writing Functions-reusable piece of code. for ex: instead of repeatedly writing 
x * 2
def double(x):
    return x * 2
    double(5)

In [ ]:
#Parameters; a = parameter, b = parameter
def add(a, b):
    return a + b

add(10, 20)
#calculate percentage change repeatedly
def percentage_change(old, new):
    return ((new - old) / old) * 100

percentage_change(100, 120)

In [53]:
#Strings and F-strings
name = "Neha"
print("Hello", name)
age = 25
print(f"My age is {age}")

#Another example
name = "Neha"
age = 25
income = 50000

print(f"{name} is {age} years old and earns {income}.")

Hello Neha
My age is 25
Neha is 25 years old and earns 50000.

In [54]:
#formatting numbers
income = 52345.6789
print(f"Income = {income:.2f}")

Income = 52345.68

In [55]:
rate = 0.2567
print(f"Rate = {rate:.2%}")

Rate = 25.67%

In [1]:
import pandas as pd

In [48]:
# Fast numerical calculations, Used for:Statistics,Linear algebra,Econometrics preprocessing,Arrays,Matrix operations,Mathematical functions
import numpy as np
a = np.array([1, 2, 3])
print(a.mean())
print(a.sum())

2.0
6

In [ ]:
student

In [3]:
income = np.array([25000, 30000, 35000, 40000])

In [4]:
income

array([25000, 30000, 35000, 40000])

In [5]:
income.mean()

np.float64(32500.0)

In [11]:
type(income.mean())

numpy.float64

In [12]:
income.min()

np.int64(25000)

In [13]:
income.max()

np.int64(40000)

In [14]:
income.sum()

np.int64(130000)

In [4]:
#pandas data frame looks like as excel table
import pandas as pd

In [ ]:
#Creates:Histograms Scatterplots Line graphs Bar charts, Creates:Histograms Scatterplots Line graphs Bar charts
import matplotlib.pyplot as plt

In [5]:
data = {
    "Age": [21, 22, 23, 24],
    "Education": [12, 14, 16, 18],
    "Income": [20000, 30000, 40000, 50000]
}

df = pd.DataFrame(data)

In [21]:
df

   Age  Education  Income
0   21         12   20000
1   22         14   30000
2   23         16   40000
3   24         18   50000

In [23]:
#selecting columns
df["Income"]

0    20000
1    30000
2    40000
3    50000
Name: Income, dtype: int64

In [26]:
#multiple columns
df[["Age", "Income"]]

   Age  Income
0   21   20000
1   22   30000
2   23   40000
3   24   50000

In [27]:
#basic descriptive analysis
df["Age"].mean()

np.float64(22.5)

In [34]:
df["Age"].median()

22.5

In [35]:
df["Age"].min()

21

In [36]:
df["Age"].max()

24

In [37]:
df["Age"].var()

1.6666666666666667

In [39]:
df["Age"].std()

1.2909944487358056

In [41]:
#Describe provides:count, mean,standard deviation,minimum,25th percentile,median,75th percentile, maximum
df["Age"].describe()

count     4.000000
mean     22.500000
std       1.290994
min      21.000000
25%      21.750000
50%      22.500000
75%      23.250000
max      24.000000
Name: Age, dtype: float64

In [42]:
df["Income"].describe()

count        4.000000
mean     35000.000000
std      12909.944487
min      20000.000000
25%      27500.000000
50%      35000.000000
75%      42500.000000
max      50000.000000
Name: Income, dtype: float64

In [43]:
df.describe()

             Age  Education        Income
count   4.000000   4.000000      4.000000
mean   22.500000  15.000000  35000.000000
std     1.290994   2.581989  12909.944487
min    21.000000  12.000000  20000.000000
25%    21.750000  13.500000  27500.000000
50%    22.500000  15.000000  35000.000000
75%    23.250000  16.500000  42500.000000
max    24.000000  18.000000  50000.000000

In [50]:
#Check missing values
df.isna()

     Age  Education  Income
0  False      False   False
1  False      False   False
2  False      False   False
3  False      False   False

In [ ]:
df.dataframe.loc

In [51]:
#tells us how many missing observations each variable contains.
df.isna().sum()

Age          0
Education    0
Income       0
dtype: int64

In [ ]:
#percentage of missing values
df.isna().mean() * 100

In [52]:
#removing missing observation
df.dropna()

   Age  Education  Income
0   21         12   20000
1   22         14   30000
2   23         16   40000
3   24         18   50000

In [53]:
#missing imputation
df["Income"].fillna(df["Income"].mean())

0    20000
1    30000
2    40000
3    50000
Name: Income, dtype: int64

In [56]:
#check duplicates row
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [54]:
#count duplicates
df.duplicated().sum()

np.int64(0)

In [55]:
#drop duplicates
df = df.drop_duplicates()

In [ ]:
#data inspection
df.head() #SHOWS FIRST 5 OBSERVATION
df.head(10) #shows first 10 observations
df.tail() #shows the last 5 observations
df.shape #rows and columns
df.columns #shows variable names
df.index 
df.info() #tells about variable names, no of missing observations, datatype, memory usage
df.describe() #provides count, mean, std, min, 25%, 50%, 75%, max
df.dtypes

In [ ]:
#selcting data
df["variable"]
df[["var1", "var2"]]
df.loc[]
df.iloc[]

In [ ]:
#missing values
df.isna()
df.isna().sum()
df.notna()
df.dropna()
df.fillna()

In [ ]:
#duplicates
df.duplicated()
df.duplicated().sum()
df.drop_duplicates()

In [ ]:
#descriptive statistics
df.mean()
df.median()
df.std()
df.var()
df.min()
df.max()
df.sum()
df.count()

In [57]:
#sorting
df.sort_values("Income")
df.sort_values("Income", ascending=False)

   Age  Education  Income
3   24         18   50000
2   23         16   40000
1   22         14   30000
0   21         12   20000

In [12]:
df.sort_values("Income", ascending=True)

   Age  Education  Income
0   21         12   20000
1   22         14   30000
2   23         16   40000
3   24         18   50000

In [13]:
#Filtering
df[df["Age"] > 30]

Empty DataFrame
Columns: [Age, Education, Income]
Index: []

In [14]:
#Multiple conditions
df[(df["Age"] > 30) & (df["Income"] > 50000)]

Empty DataFrame
Columns: [Age, Education, Income]
Index: []

In [ ]:
#Grouping
df.groupby("Gender")["Income"].mean()

In [24]:
type(Income)

NameError: name 'Income' is not defined

In [45]:
#Importing seaborn
import seaborn as sns
# See available datasets
sns.get_dataset_names()
#loading the particular dataset
titanic = sns.load_dataset("titanic")
titanic.head()
#Seeing the complete daatset
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [22]:
#statsmodels — especially useful for Econometrics
import statsmodels.api as sm

data = sm.datasets.get_rdataset("Guerry", "HistData").data

data.head()
data.tail()
data.shape()
#seeing the variables
data.columns

Index(['dept', 'Region', 'Department', 'Crime_pers', 'Crime_prop', 'Literacy',
       'Donations', 'Infants', 'Suicides', 'MainCity', 'Wealth', 'Commerce',
       'Clergy', 'Crime_parents', 'Infanticide', 'Donation_clergy', 'Lottery',
       'Desertion', 'Instruction', 'Prostitutes', 'Distance', 'Area',
       'Pop1831'],
      dtype='object')

In [68]:
import statsmodels.formula.api as smf

In [ ]:
#Iris dataset — excellent for regression/classification
from sklearn.datasets import load_iris
iris = load_iris()
print(iris)
#To convert it into a Pandas DataFrame:
import pandas as pd

iris_df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)
iris_df.head()
#Adding the dependent variable
iris_df["target"] = iris.target
iris_df.head()

In [ ]:
#Basic data analysis 
import seaborn as sns
tips = sns.load_dataset("tips")
tips.head()
tips.describe()
# calculate average tip
tips["tip"].mean()
#average bill by day
tips.groupby("day")["total_bill"].mean()

In [62]:
data = pd.read_csv("Census Data.csv"/)

In [ ]:
pd.read(

In [ ]:
#Skip rows
df = pd.read_csv(
    "data.csv",
    header=None
)

In [ ]:
df = pd.read_csv(
    "data.csv",
    skiprows=2
)

In [ ]:
#Select only certain column
df = pd.read_csv(
    "data.csv",
    usecols=["Age", "Education", "Income"]
)

In [ ]:
df.to_csv("clean_data.csv", index=False) #saving data in the form of CSV, INDEX=False prevents pandas from writing its row index as an additional column

In [ ]:
df.to_excel("clean_data.xlsx", index=False)

In [ ]:
import os
os.getcwd() #working directory

In [ ]:
os.listdir() #seeing other files in the current folder

In [72]:
data1 = pd.read_csv("D:/Computational methods in Economics/Census Data.csv")

In [74]:
data.describe()

,Community Area Number,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
count,77.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,77.000000
mean,39.000000,4.920513,21.739744,15.341026,20.330769,35.717949,25597.000000,49.506494
std,22.371857,3.658981,11.457231,7.499497,11.746514,7.284421,15196.405541,28.690556
min,1.000000,0.300000,3.300000,4.700000,2.500000,13.500000,8201.000000,1.000000
25%,20.000000,2.325000,13.350000,9.200000,12.075000,32.150000,15804.750000,25.000000
50%,39.000000,3.850000,19.050000,13.850000,18.650000,38.050000,21668.500000,50.000000
75%,58.000000,6.800000,29.150000,20.000000,26.600000,40.500000,28715.750000,74.000000
max,77.000000,15.800000,56.500000,35.900000,54.800000,51.500000,88669.000000,98.000000

In [ ]:
df = pd.read_excel(
    "data.xlsx",
    sheet_name="Sheet1"
)

In [ ]:
sheets = pd.read_excel(
    "FILENAME",
    sheet_name=None
)

In [ ]:
df = pd.read_stata("FILENAME.dta")

In [ ]:
df = pd.read_json("data.json")

In [63]:
data.head()

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
0,1.0,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39.0
1,2.0,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46.0
2,3.0,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20.0
3,4.0,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17.0
4,5.0,North Center,0.3,7.5,5.2,4.5,26.2,57123,6.0

In [9]:
data.columns

Index(['Community Area Number', 'COMMUNITY AREA NAME',
       'PERCENT OF HOUSING CROWDED', 'PERCENT HOUSEHOLDS BELOW POVERTY',
       'PERCENT AGED 16+ UNEMPLOYED',
       'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA',
       'PERCENT AGED UNDER 18 OR OVER 64', 'PER CAPITA INCOME ',
       'HARDSHIP INDEX'],
      dtype='object')

In [64]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Community Area Number                         77 non-null     float64
 1   COMMUNITY AREA NAME                           78 non-null     object
 2   PERCENT OF HOUSING CROWDED                    78 non-null     float64
 3   PERCENT HOUSEHOLDS BELOW POVERTY              78 non-null     float64
 4   PERCENT AGED 16+ UNEMPLOYED                   78 non-null     float64
 5   PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA  78 non-null     float64
 6   PERCENT AGED UNDER 18 OR OVER 64              78 non-null     float64
 7   PER CAPITA INCOME                             78 non-null     int64
 8   HARDSHIP INDEX                                77 non-null     float64
dtypes: float64(7), int64(1), object(1)
memory usage: 5.6+ KB

In [14]:
data.shape

(78, 9)

Understand Data Types

In [16]:
data.dtypes

Community Area Number                           float64
COMMUNITY AREA NAME                              object
PERCENT OF HOUSING CROWDED                      float64
PERCENT HOUSEHOLDS BELOW POVERTY                float64
PERCENT AGED 16+ UNEMPLOYED                     float64
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA    float64
PERCENT AGED UNDER 18 OR OVER 64                float64
PER CAPITA INCOME                                 int64
HARDSHIP INDEX                                  float64
dtype: object

Complete Dataset Summary

In [65]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Community Area Number                         77 non-null     float64
 1   COMMUNITY AREA NAME                           78 non-null     object
 2   PERCENT OF HOUSING CROWDED                    78 non-null     float64
 3   PERCENT HOUSEHOLDS BELOW POVERTY              78 non-null     float64
 4   PERCENT AGED 16+ UNEMPLOYED                   78 non-null     float64
 5   PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA  78 non-null     float64
 6   PERCENT AGED UNDER 18 OR OVER 64              78 non-null     float64
 7   PER CAPITA INCOME                             78 non-null     int64
 8   HARDSHIP INDEX                                77 non-null     float64
dtypes: float64(7), int64(1), object(1)
memory usage: 5.6+ KB

Checking a missing value

In [67]:
data.isnull().sum()

Community Area Number                           1
COMMUNITY AREA NAME                             0
PERCENT OF HOUSING CROWDED                      0
PERCENT HOUSEHOLDS BELOW POVERTY                0
PERCENT AGED 16+ UNEMPLOYED                     0
PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA    0
PERCENT AGED UNDER 18 OR OVER 64                0
PER CAPITA INCOME                               0
HARDSHIP INDEX                                  1
dtype: int64

View Statistical Summary

In [19]:
data.describe()

,Community Area Number,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
count,77.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,77.000000
mean,39.000000,4.920513,21.739744,15.341026,20.330769,35.717949,25597.000000,49.506494
std,22.371857,3.658981,11.457231,7.499497,11.746514,7.284421,15196.405541,28.690556
min,1.000000,0.300000,3.300000,4.700000,2.500000,13.500000,8201.000000,1.000000
25%,20.000000,2.325000,13.350000,9.200000,12.075000,32.150000,15804.750000,25.000000
50%,39.000000,3.850000,19.050000,13.850000,18.650000,38.050000,21668.500000,50.000000
75%,58.000000,6.800000,29.150000,20.000000,26.600000,40.500000,28715.750000,74.000000
max,77.000000,15.800000,56.500000,35.900000,54.800000,51.500000,88669.000000,98.000000

Understand Categories

In [20]:
data["PERCENT HOUSEHOLDS BELOW POVERTY"].unique()

array([23.6, 17.2, 24. , 10.9,  7.5, 11.4, 12.3, 12.9,  3.3,  5.4,  8.6,
       13.2, 19.2, 11.6, 13.1, 10.6, 15.3, 18.7, 20.5, 16.8, 33.9, 14.7,
       28.6, 41.7, 42.4, 20.6, 43.1, 30.7, 25.8, 13.8, 40.1, 29.6, 39.7,
       51.2, 29.3, 21.7, 42.1, 18.4, 31.1, 27.8, 29.8, 33. , 11.5, 19.8,
       21.6, 29.2, 25.9, 56.5, 17.1,  8.8, 14.1, 18.9, 29. , 15.6, 23.4,
        8.9, 14.9, 27.9, 34.4, 46.6, 10.4, 27.6,  5.1, 16.9,  3.4, 15.4,
       18.2, 19.7])

In [21]:
data["PERCENT HOUSEHOLDS BELOW POVERTY"].value_counts()

PERCENT HOUSEHOLDS BELOW POVERTY
23.6    2
29.6    2
18.7    2
15.3    2
30.7    2
       ..
39.7    1
51.2    1
21.7    1
42.1    1
19.7    1
Name: count, Length: 68, dtype: int64

Select One Column

In [22]:
data["HARDSHIP INDEX"]

0     39.0
1     46.0
2     20.0
3     17.0
4      6.0
      ...
73    16.0
74    30.0
75    24.0
76    19.0
77     NaN
Name: HARDSHIP INDEX, Length: 78, dtype: float64

Check Random Records

In [23]:
data.sample(10)

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
58,59.0,McKinley Park,7.2,18.7,13.4,32.9,35.6,16954,61.0
36,37.0,Fuller Park,3.2,51.2,33.9,26.6,44.9,10432,97.0
41,42.0,Woodlawn,2.9,30.7,23.4,16.5,36.1,18672,58.0
32,33.0,Near South Side,1.3,13.8,4.9,7.4,21.8,59077,7.0
30,31.0,Lower West Side,9.6,25.8,15.8,40.7,32.6,16444,76.0
43,44.0,Chatham,3.3,27.8,24.0,14.5,40.3,18881,60.0
16,17.0,Dunning,5.2,10.6,10.0,16.2,33.6,26282,28.0
54,55.0,Hegewisch,3.3,17.1,9.6,19.2,42.9,22677,44.0
72,73.0,Washington Height,1.1,16.9,20.8,13.7,42.6,19713,48.0
39,40.0,Washington Park,5.6,42.1,28.6,25.4,42.8,13785,88.0

In [26]:
data["percent CROWDED"] = pd.cut(
    data["PERCENT OF HOUSING CROWDED"],
    bins=[1,3,5,9],
    labels=["Low","Medium","High"])

In [28]:
data["percent CROWDED"].value_counts()

percent CROWDED
Low       22
Medium    22
High      19
Name: count, dtype: int64

In [29]:
data["COMMUNITY AREA NAME"].value_counts()

COMMUNITY AREA NAME
Rogers Park           1
Pullman               1
Archer Heights        1
Garfield Ridge        1
Hegewisch             1
                     ..
West Garfield Park    1
Austin                1
West Town             1
Humboldt park         1
CHICAGO               1
Name: count, Length: 78, dtype: int64

In [30]:
data["percent CROWDED"].value_counts(normalize=True)*100

percent CROWDED
Low       34.920635
Medium    34.920635
High      30.158730
Name: proportion, dtype: float64

Descriptive statistics

In [31]:
data["percent CROWDED"].describe()

count      63
unique      3
top       Low
freq       22
Name: percent CROWDED, dtype: object

In [ ]:
data["percent CROWDED"].mean()
data["Income"].median()
data["Income"].mode()
data["Income"].std()
data.groupby("City")["Income"].mean()
data.groupby("Department")["Salary"].mean()
#Cross-tabulation
pd.crosstab(
data["Gender"],
data["Purchased"]
)
#Correlation
data[["Age","Income"]].corr()
import seaborn as sns
sns.heatmap(data.corr(numeric_only=True), annot=True)*

In [ ]:
from sklearn.dataset import load_iris

In [ ]:
data= sns.load_dataset("titanic")

In [3]:
import seaborn as sns

In [ ]:
sns.get_dataset_names()

In [6]:
titanic = sns.load_dataset("titanic")

In [7]:
healthexp = sns.load_dataset("healthexp")

In [8]:
healthexp.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [9]:
healthexp

     Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]

In [ ]:
#steps to start working on any datafile
import pandas as pd
import numpy as np
import os
print(os.getcwd())
print(os.listdir())
df = pd.read_csv("data.csv")
df.head()
df.shape
df.columns
df.info()
df.describe()
df.isna().sum()
df.duplicated().sum()

In [87]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

In [86]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

In [3]:
import pandas as pd

In [ ]:
pd.read_spss

In [ ]:
help(sum)

In [ ]:
help(pd.read_csv)

In [ ]:
pd.read_csv?

In [ ]:
pd.DataFrame?

In [ ]:
pd.read_csv(
#shift+tab will display information about the fucntion and the parameters

In [99]:
import pandas as pd

In [ ]:
pd.read_table(%pprint
#tab completion-press tab

In [ ]:
#Searching for a function when you don't know its name
look for documentation

In [105]:
df.h
#tab completion for data frame

<bound method NDFrame.head of    Age  Education  Income
0   21         12   20000
1   22         14   30000
2   23         16   40000
3   24         18   50000>

In [ ]:
#how to learn to use 
df.groupby?

In [ ]:
df.groupby??

In [ ]:
df.groupby(
#shift + Tab and then search Pandas groupby examples

In [ ]:
#python help toolkit
| What you want            | What to use     |
| ------------------------ | --------------- |
| General Python help      | `help()`        |
| Jupyter documentation    | `?`             |
| Source code              | `??`            |
| Function arguments       | `Shift + Tab`   |
| Find available methods   | `Tab`           |
| Find object's attributes | `dir()`         |
| Find object's type       | `type()`        |
| See DataFrame structure  | `df.info()`     |
| See first observations   | `df.head()`     |
| See statistical summary  | `df.describe()` |

In [ ]:
help(df.series.median)

In [112]:
import pandas as pd

In [ ]:
help(pd.mean)

In [ ]:
help(np.mean)

In [118]:
marks = [10, 20, 30, 40, 50]

In [119]:
#pandas has a built in sum(), mean isn't
x=sum(marks)

In [ ]:
help(sum)

In [ ]:
#NumPy has a mean() function
np.mean([10, 20, 30, 40, 50])
help(np.mean)
np.mean

In [ ]:
#in panda series
marks_series = pd.Series(marks)
marks_series.mean()
marks_series.mean?
help(marks_series.mean)

In [25]:
#Look for dropping obeservation but getting counted again in the dataset; Changing type of variable not converting string to float/numeric

In [ ]:
df.loc[7]

In [ ]:
#.loc — label-based selection, selects rows and columns based on their labels/names.
#general synatx: df.loc[row_label, column_label]
df.loc[1, 'Name'] #Go to the row whose label is 1 and the column whose label is Name."
df.loc[1] # selecting a complete row
df.loc[[0, 2]] #selects rows with labels 0 and 2
df.loc[:, 'Name'] #selecting columns using .loc; Select all rows and the column called Name.
df.loc[:, ['Name', 'Income']] #multiple columns
df.loc[1:3] #.loc with a range-including the starting and ending labels

In [ ]:
# .iloc — position-based selection, integer location, physical position of the row or column
df.iloc[row_position, column_position] #general syntax
df.iloc[1,0]
df.iloc[1] #selecting rows with .iloc
df.iloc[[0, 2]] #selecting multiple rows with .iloc
df.iloc[:, 0] #selecting columns with .iloc
df.iloc[:, 1:3] #selecting columns with a range .iloc

In [ ]:
#difference between .loc and .iloc
df.loc[1:3] #the ending value is included, inclusive
df.iloc[1:3] #the ending value is excluded, exclusive, useful when you care baout positions

In [ ]:
df.loc[df['Age'] > 21]
df.loc[df['Age'] > 21, ['Name', 'Income']] #selecting specific columns
#modifying .loc to modify the data
df.loc[df['Gender'] == 'Female', 'Gender'] = 'F' #conditional assignment

In [ ]:
df.iloc[:3] #first three observations
df.iloc[-2:] #last 2 observations
df.iloc[:, :2] #first two columns
df.iloc[1:4, 0:3] #rows1-3, columns0-2

In [ ]:
#Slicing means selecting a specific portion of a DataFrame.
df.iloc[:3] #selcting first three rows
df.iloc[1:4] #selecting 2-4row
df[['Name', 'Age']] #select particular column
df.iloc[0:3, 0:2] #selecting particular rows and columns together

In [ ]:
#Sorting means arranging observations according to a variable.
df.sort_values('Age')
df.sort_values('Age', ascending=False) #sorting highest to lowest
df.sort_values('Income', ascending=False) #sorting highest to lowest
df.sort_values(['Gender', 'Income']) #sorting by multiple variables

df.sort_values(
    ['Gender', 'Income'],
    ascending=[True, False]
)

In [ ]:
#Ranking assigns a numerical rank to observations.
df['Income_Rank'] = df['Income'].rank(
    ascending=False
)
#The person with the highest income gets rank 1.

In [ ]:
df[['Name', 'Income', 'Income_Rank']]

In [ ]:
#different approaches to rank
df['Income'].rank(method='average') 
#method='min'
#method='max'
#method='first'
#method='dense'

In [ ]:
#Creating Variables and Aggregating
df['Income'] 
df['Income_000'] = df['Income'] / 1000 #changing income into thousands

In [ ]:
#Creating variables using conditions
df['High_Income'] = df['Income'] > 30000 #classify people according to income

In [ ]:
df['Income_Group'] = df['Income'].apply(
    lambda x: 'High' if x >= 30000 else 'Low'
)

In [ ]:
# .apply() applies a function to every value in a Series or to every row/column of a DataFrame
df['Age_Squared'] = df['Age'].apply(
    lambda x: x**2
)
#this will create Age^2

In [ ]:
df.apply

In [ ]:
#A lambda function is a small anonymous function.
def square(x):
    return x**2

In [ ]:
#the same can be written as
lambda x: x**2

In [ ]:
df['Age_Squared'] = df['Age'].apply(
    lambda x: x**2
) 
#this takes each age and calculates its square

In [ ]:
df['Income_Annual'] = df['Income'].apply(
    lambda x: x * 12
)

In [ ]:
#groupby() allows us to divide data into groups and calculate statistics separately for each group
df.groupby('Gender')['Income'].mean() 
#what is the average income separately for males and females?

In [ ]:
#multiple summary statistics
df.groupby('Gender')['Income'].agg(
    ['mean', 'median', 'min', 'max', 'count']
)

In [ ]:
#grouping by more than one variable
df.groupby(['Gender', 'Age'])['Income'].mean()
#calculates the mean income for every combination of gender*age

In [ ]:
#pivot table is a tool for summarising and reorganising data based on one or more categorical variables.
#Basic syntax
pd.pivot_table(
    data,
    values,
    index,
    columns,
    aggfunc
)
#| Argument  | Meaning                   |
| --------- | ------------------------- |
| `data`    | DataFrame                 |
| `values`  | Variable to summarise     |
| `index`   | Variable used for rows    |
| `columns` | Variable used for columns |
| `aggfunc` | Statistical function      |

In [5]:
#Creating a dataset
import pandas as pd
df = pd.DataFrame({
    'Gender': ['Male','Female','Male','Female','Male',
               'Female','Male','Female','Male','Female'],
    
    'Education': ['Graduate','Graduate','Postgraduate',
                  'Postgraduate','Graduate','Postgraduate',
                  'Graduate','Graduate','Postgraduate','Graduate'],
    
    'State': ['AP','AP','AP','AP','Telangana',
              'Telangana','Telangana','Telangana','AP','Telangana'],
    
    'Income': [30000,35000,45000,50000,28000,
               48000,32000,36000,42000,34000],
    
    'Age': [25,27,32,30,24,35,26,29,34,23]
})

In [6]:
#A simple pivot table
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    aggfunc='mean'
)
#Group observations by Gender and calculate the mean Income.

         Income
Gender
Female  40600.0
Male    35400.0

In [46]:
df

   Gender     Education      State  Income  Age
0    Male      Graduate         AP   30000   25
1  Female      Graduate         AP   35000   27
2    Male  Postgraduate         AP   45000   32
3  Female  Postgraduate         AP   50000   30
4    Male      Graduate  Telangana   28000   24
5  Female  Postgraduate  Telangana   48000   35
6    Male      Graduate  Telangana   32000   26
7  Female      Graduate  Telangana   36000   29
8    Male  Postgraduate         AP   42000   34
9  Female      Graduate  Telangana   34000   23

In [7]:
#Pivot table with columns
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    columns='Education',
    aggfunc='mean'
)

Education  Graduate  Postgraduate
Gender
Female      35000.0       49000.0
Male        30000.0       43500.0

In [ ]:
#Difference betwee index and columns
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    columns='Education',
    aggfunc='mean'
)
#the above code considers Gender as rows, education as columns, income is the varaible that is being summarised and mean is calculated

In [8]:
#medium
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    aggfunc='median'
)

         Income
Gender
Female  36000.0
Male    32000.0

In [10]:
#minimum
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    aggfunc='min'
)

        Income
Gender
Female   34000
Male     28000

In [11]:
#maximum
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    aggfunc='max'
)

        Income
Gender
Female   50000
Male     45000

In [12]:
#sum
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    aggfunc='sum'
)

        Income
Gender
Female  203000
Male    177000

In [ ]:
#count
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    aggfunc='count'
)

In [ ]:
#multiple statistics at once
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    aggfunc=['mean', 'median', 'min', 'max', 'count']
)

In [13]:
#If in case i want to summarise income and age both at once
pd.pivot_table(
    df,
    values=['Income', 'Age'],
    index='Gender',
    aggfunc='mean'
)

         Age   Income
Gender
Female  28.8  40600.0
Male    28.2  35400.0

In [14]:
#If in case i want to average income by state and gender at once
pd.pivot_table(
    df,
    values='Income',
    index=['State', 'Gender'],
    aggfunc='mean'
)
#This is called MultiIndex as the result is hierarchical/multiindex in nature

                        Income
State     Gender
AP        Female  42500.000000
          Male    39000.000000
Telangana Female  39333.333333
          Male    30000.000000

In [ ]:
#we can have multiple variables in the columns
pd.pivot_table(
    df,
    values='Income',
    index='State',
    columns=['Gender', 'Education'],
    aggfunc='mean'
)
#useful for multidimensional descriptive analysis

In [15]:
#Adding margins-Totals
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    columns='Education',
    aggfunc='mean',
    margins=True
)
#All row containing the overall mean.useful for comparing the subgroups mean and overall mean

Education  Graduate  Postgraduate      All
Gender
Female      35000.0       49000.0  40600.0
Male        30000.0       43500.0  35400.0
All         32500.0       46250.0  38000.0

In [16]:
#changing the names of the total
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    columns='Education',
    aggfunc='mean',
    margins=True,
    margins_name='Total'
)

Education  Graduate  Postgraduate    Total
Gender
Female      35000.0       49000.0  40600.0
Male        30000.0       43500.0  35400.0
Total       32500.0       46250.0  38000.0

In [18]:
#handling missing values from pivot table
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    columns='Education',
    aggfunc='mean',
    dropna=False
)

Education  Graduate  Postgraduate
Gender
Female      35000.0       49000.0
Male        30000.0       43500.0

In [ ]:
#Filling empty cells with Zeroes
pd.pivot_table(
    df,
    values='Income',
    index='Gender',
    columns='Education',
    aggfunc='mean',
    fill_value=0
)

In [19]:
#Multiple functions for different values
pd.pivot_table(
    df,
    values=['Income', 'Age'],
    index='Gender',
    aggfunc={
        'Income': ['mean', 'median'],
        'Age': ['mean', 'min', 'max']
    }
)

       Age             Income
       max  mean min     mean   median
Gender
Female  35  28.8  23  40600.0  36000.0
Male    34  28.2  24  35400.0  32000.0

In [37]:
#Pivot tables for count
pd.pivot_table(
    df,
    index='Gender',
    columns='Education',
    values='Income',
    aggfunc='count'
)
#This counts the non-missing values for Income

Education  Graduate  Postgraduate
Gender
Female            3             2
Male              3             2

In [ ]:
#Pivot tables for percentages
table = pd.pivot_table(
    df,
    values='Count',
    index='Gender',
    columns='Education',
    aggfunc='sum',
    fill_value=0
)

In [43]:
#calculating row percenatage
row_percent = table.div(
    table.sum(axis=1),
    axis=0
) * 100

In [44]:
column_percent = table.div(
    table.sum(axis=0),
    axis=1
) * 100

In [50]:
import pandas as pd

df = pd.DataFrame({
    'Gender': [
        'Male', 'Female', 'Male', 'Female',
        'Male', 'Female', 'Male', 'Female',
        'Male', 'Female'
    ],

    'Education': [
        'Graduate', 'Graduate', 'Postgraduate',
        'Graduate', 'Graduate', 'Postgraduate',
        'Postgraduate', 'Graduate',
        'Graduate', 'Postgraduate'
    ],

    'Hypertension': [
        'Yes', 'No', 'Yes', 'Yes',
        'No', 'Yes', 'Yes', 'No',
        'No', 'Yes'
    ],

    'State': [
        'AP', 'AP', 'AP', 'AP',
        'Telangana', 'Telangana',
        'Telangana', 'Telangana',
        'AP', 'Telangana'
    ]
})

In [52]:
df

   Gender     Education Hypertension      State
0    Male      Graduate          Yes         AP
1  Female      Graduate           No         AP
2    Male  Postgraduate          Yes         AP
3  Female      Graduate          Yes         AP
4    Male      Graduate           No  Telangana
5  Female  Postgraduate          Yes  Telangana
6    Male  Postgraduate          Yes  Telangana
7  Female      Graduate           No  Telangana
8    Male      Graduate           No         AP
9  Female  Postgraduate          Yes  Telangana

In [53]:
pd.crosstab(
    df['Gender'],
    df['Hypertension']
)

Hypertension  No  Yes
Gender
Female         2    3
Male           2    3

In [55]:
#Crosstabulation:distribution of obervations across combinations of categorical variables
pd.crosstab(
    index= df['Gender'],
    columns=df['Education']
)

Education  Graduate  Postgraduate
Gender
Female            3             2
Male              3             2

In [58]:
pd.crosstab(df.Gender, df.Education)

Education  Graduate  Postgraduate
Gender
Female            3             2
Male              3             2

In [61]:
#changing the direction
pd.crosstab(df.Education, df.Gender)

Gender        Female  Male
Education
Graduate           3     3
Postgraduate       2     2

In [62]:
#Cross-tab with more than two varaibles
pd.crosstab(
    index=[df['State'], df['Gender']],
    columns=df['Education']
)

Education         Graduate  Postgraduate
State     Gender
AP        Female         2             0
          Male           2             1
Telangana Female         1             2
          Male           1             1

In [63]:
#what if you want percentage instead of COUNTS
pd.crosstab(
    df['Gender'],
    df['Education'],
    normalize='index'
) * 100
#this calculates row percentage

Education  Graduate  Postgraduate
Gender
Female         60.0          40.0
Male           60.0          40.0

In [65]:
pd.crosstab(
    df['Gender'],
    df['Education'],
    normalize='columns'
) * 100
#this calculates column percentage

Education  Graduate  Postgraduate
Gender
Female         50.0          50.0
Male           50.0          50.0

In [67]:
pd.crosstab(
    df['Gender'],
    df['Education'],
    normalize=True
) * 100
#this calculates overall percentage

Education  Graduate  Postgraduate
Gender
Female         30.0          20.0
Male           30.0          20.0

In [68]:
#Adding totals using mrargins=True
pd.crosstab(
    df['Gender'],
    df['Education'],
    margins=True
)

Education  Graduate  Postgraduate  All
Gender
Female            3             2    5
Male              3             2    5
All               6             4   10

In [69]:
#Renaming the totals
pd.crosstab(
    df['Gender'],
    df['Education'],
    margins=True,
    margins_name='Total'
)

Education  Graduate  Postgraduate  Total
Gender
Female            3             2      5
Male              3             2      5
Total             6             4     10

In [70]:
#Count and percentage together
count_table = pd.crosstab(
    df['Gender'],
    df['Education']
)

In [71]:
count_table

Education  Graduate  Postgraduate
Gender
Female            3             2
Male              3             2

In [75]:
count_table = pd.crosstab(
    df['Gender'],
    df['Education'],
    normalize='index'
) *100

In [76]:
count_table

Education  Graduate  Postgraduate
Gender
Female         60.0          40.0
Male           60.0          40.0

In [79]:
#Cross-tab with a different variable, For instance, gender*educatio separately for states
pd.crosstab(
    index= [df.State, df.Gender],
    columns=df.Education    
)

Education         Graduate  Postgraduate
State     Gender
AP        Female         2             0
          Male           2             1
Telangana Female         1             2
          Male           1             1

In [80]:
#Taking multiple variables in the columns
pd.crosstab(
    index=df['Gender'],
    columns=[df['State'], df['Education']]
)

State           AP              Telangana
Education Graduate Postgraduate  Graduate Postgraduate
Gender
Female           2            0         1            2
Male             2            1         1            1

In [82]:
df

   Gender     Education Hypertension      State
0    Male      Graduate          Yes         AP
1  Female      Graduate           No         AP
2    Male  Postgraduate          Yes         AP
3  Female      Graduate          Yes         AP
4    Male      Graduate           No  Telangana
5  Female  Postgraduate          Yes  Telangana
6    Male  Postgraduate          Yes  Telangana
7  Female      Graduate           No  Telangana
8    Male      Graduate           No         AP
9  Female  Postgraduate          Yes  Telangana

In [ ]:
pd.crosstab(
    df['Gender'],
    df['Education'],
    values=df['Income'],
    aggfunc='mean'
)

In [ ]:
#Aggregate functions
pd.crosstab(
    df['Gender'],
    df['Education'],
    values=df['Income'],
    aggfunc='median'
)

In [ ]:
#Multiple aggregate functions together
pd.crosstab(
    df['Gender'],
    df['Education'],
    values=df['Income'],
    aggfunc=['mean', 'median']
)

In [89]:
#cross-tabulation with a custom function
def age_range(x):
    return x.max() - x.min()

In [ ]:
pd.crosstab(
    df['Gender'],
    df['Education'],
    values=df['Age'],
    aggfunc=age_range
)

In [92]:
#Performing chi2 test after cross-tab
from scipy.stats import chi2_contingency

chi2, p, dof, expected = chi2_contingency(table)

print("Chi-square:", chi2)
print("p-value:", p)
print("Degrees of freedom:", dof)

Chi-square: 29.053937053796837
p-value: 7.03909026283918e-08
Degrees of freedom: 1

In [ ]:
#Combining datasets: Merge, join and Concatenate. They all require a common variable prefreable an ID/key
#merge() is used when two datasets need to be combined based on a common key/column.Match these rows based on ID.
#Join() is primarily used to combine DataFrames based on their index, although it can also join using columns.Match these rows using their index.
#concat() is used to stack datasets. Put these datasets together one after another or side by side.

In [93]:
import pandas as pd

df1 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Amit', 'Neha', 'Rahul', 'Priya'],
    'Gender': ['Male', 'Female', 'Male', 'Female']
})

df2 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Income': [25000, 35000, 28000, 40000],
    'Education': ['Graduate', 'Postgraduate',
                  'Graduate', 'Postgraduate']
})

In [94]:
df1

    ID   Name  Gender
0  101   Amit    Male
1  102   Neha  Female
2  103  Rahul    Male
3  104  Priya  Female

In [95]:
df2

    ID  Income     Education
0  101   25000      Graduate
1  102   35000  Postgraduate
2  103   28000      Graduate
3  104   40000  Postgraduate

In [96]:
df = pd.merge(df1, df2, on='ID')

In [101]:
df

    ID   Name  Gender  Income     Education
0  101   Amit    Male   25000      Graduate
1  102   Neha  Female   35000  Postgraduate
2  103  Rahul    Male   28000      Graduate
3  104  Priya  Female   40000  Postgraduate

In [ ]:
#Types of merge:inner, left, right and outer joins

In [ ]:
#Inner merge: Keep only observations present in both datasets.inner=intersection
pd.merge(
    df1,
    df2,
    on='ID',
    how='inner'
)

In [ ]:
#left merge: Keep every observation from the left DataFrame (df1).
pd.merge(
    df1,
    df2,
    on='ID',
    how='left'
)

In [ ]:
#right merge: preserve everything in the right dataset
pd.merge(
    df1,
    df2,
    on='ID',
    how='right'
)

In [ ]:
#Outer merge: This keeps everything from both datasets. Outer=union, all ids from both datasets are retained
pd.merge(
    df1,
    df2,
    on='ID',
    how='outer'
)

In [ ]:
#bydefault merge-inner
pd.merge(df1, df2, on='ID')

In [ ]:
#if in case the common variable has different names
pd.merge(
    df1,
    df2,
    left_on='Person_ID',
    right_on='ID'
)

In [ ]:
#if in case there are multiple keys/identifiers such as state, district
pd.merge(
    df1,
    df2,
    on=['State', 'District']
)

In [ ]:
#Validating : type of relationship a. one to one, b.one to many, c.many to one, d. many to many
pd.merge(
    df1,
    df2,
    on='ID',
    validate='one_to_one'
)

In [ ]:
#how to spot duplicate keys
df1['ID'].duplicated().sum()
df2['ID'].duplicated().sum()

In [ ]:
#Find the duplicate ids
df2.loc[
    df2['ID'].duplicated(keep=False)
].sort_values('ID')

In [ ]:
#checking for a merge, this generates _merge column in the dataset with values as left only, light only, both
merged = pd.merge(
    df1,
    df2,
    on='ID',
    how='outer',
    indicator=True
)

In [ ]:
#finding unmatched observations
merged[merged['_merge'] == 'left_only'] #observations present only in DF1
merged[merged['_merge'] == 'right_only'] #observations present only in DF2
merged[merged['_merge'] == 'both'] #observations present in DF1 & DF2

In [ ]:
#join() is another way to combine DataFrames.

In [104]:
print(df)

    ID   Name  Gender  Income     Education
0  101   Amit    Male   25000      Graduate
1  102   Neha  Female   35000  Postgraduate
2  103  Rahul    Male   28000      Graduate
3  104  Priya  Female   40000  Postgraduate

In [105]:
print(df.dtypes)

ID            int64
Name         object
Gender       object
Income        int64
Education    object
dtype: object

In [109]:
print(df['Income'].dtype)

int64

In [112]:
df['Income'] = df['Income'].astype(float)

In [113]:
print(df['Income'].dtype)

float64

In [114]:
df['Income']=df['Income'].astype(str)

In [115]:
print(df['Income'].dtype)

object

In [4]:
import statsmodels.api as sm

In [ ]:
dir(sm.datasets)

In [16]:
sm.datasets.fair

In [17]:
sm.datasets.grunfeld

In [18]:
dir(sm.datasets.fair)

['COPYRIGHT',
 'DESCRLONG',
 'DESCRSHORT',
 'NOTE',
 'SOURCE',
 'TITLE',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'data',
 'load',
 'load_pandas']

In [36]:
d1 = sm.datasets.fair.load_pandas()

In [49]:
d1

In [50]:
df=d1.data

In [51]:
df

,rate_marriage,age,yrs_married,children,religious,educ,occupation,occupation_husb,affairs
0,3.0,32.0,9.0,3.0,3.0,17.0,2.0,5.0,0.111111
1,3.0,27.0,13.0,3.0,1.0,14.0,3.0,4.0,3.230769
2,4.0,22.0,2.5,0.0,1.0,16.0,3.0,5.0,1.400000
3,4.0,37.0,16.5,4.0,3.0,16.0,5.0,5.0,0.727273
4,5.0,27.0,9.0,1.0,1.0,14.0,3.0,4.0,4.666666
...,...,...,...,...,...,...,...,...,...
6361,5.0,32.0,13.0,2.0,3.0,17.0,4.0,3.0,0.000000
6362,4.0,32.0,13.0,1.0,1.0,16.0,5.0,5.0,0.000000
6363,5.0,22.0,2.5,0.0,2.0,14.0,3.0,1.0,0.000000
6364,5.0,32.0,6.0,1.0,3.0,14.0,3.0,4.0,0.000000
6365,4.0,22.0,2.5,0.0,2.0,16.0,2.0,4.0,0.000000

In [52]:
df1 = sm.datasets.get_rdataset(
    "CPS1985",
    "AER"
).data

In [53]:
df1

,wage,education,experience,age,ethnicity,region,gender,occupation,sector,union,married
rownames,,,,,,,,,,,
1,5.10,8,21,35,hispanic,other,female,worker,manufacturing,no,yes
1100,4.95,9,42,57,cauc,other,female,worker,manufacturing,no,yes
2,6.67,12,1,19,cauc,other,male,worker,manufacturing,no,no
3,4.00,12,4,22,cauc,other,male,worker,other,no,no
4,7.50,12,17,35,cauc,other,male,worker,other,no,yes
...,...,...,...,...,...,...,...,...,...,...,...
529,11.36,18,5,29,cauc,other,male,technical,other,no,no
530,6.10,12,33,51,other,other,female,technical,other,no,yes
531,23.25,17,25,48,other,other,female,technical,other,yes,yes
532,19.88,12,13,31,cauc,south,male,technical,other,yes,yes
533,15.38,16,33,55,cauc,other,male,technical,manufacturing,no,yes

In [54]:
df1

,wage,education,experience,age,ethnicity,region,gender,occupation,sector,union,married
rownames,,,,,,,,,,,
1,5.10,8,21,35,hispanic,other,female,worker,manufacturing,no,yes
1100,4.95,9,42,57,cauc,other,female,worker,manufacturing,no,yes
2,6.67,12,1,19,cauc,other,male,worker,manufacturing,no,no
3,4.00,12,4,22,cauc,other,male,worker,other,no,no
4,7.50,12,17,35,cauc,other,male,worker,other,no,yes
...,...,...,...,...,...,...,...,...,...,...,...
529,11.36,18,5,29,cauc,other,male,technical,other,no,no
530,6.10,12,33,51,other,other,female,technical,other,no,yes
531,23.25,17,25,48,other,other,female,technical,other,yes,yes
532,19.88,12,13,31,cauc,south,male,technical,other,yes,yes
533,15.38,16,33,55,cauc,other,male,technical,manufacturing,no,yes

In [55]:
type(df1)

pandas.core.frame.DataFrame

In [56]:
#understanding the data
df1.head()
df1.shape
df1.columns
df1.info()
df1.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 534 entries, 1 to 533
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   wage        534 non-null    float64
 1   education   534 non-null    int64
 2   experience  534 non-null    int64
 3   age         534 non-null    int64
 4   ethnicity   534 non-null    object
 5   region      534 non-null    object
 6   gender      534 non-null    object
 7   occupation  534 non-null    object
 8   sector      534 non-null    object
 9   union       534 non-null    object
 10  married     534 non-null    object
dtypes: float64(1), int64(3), object(7)
memory usage: 50.1+ KB

             wage   education  experience         age
count  534.000000  534.000000  534.000000  534.000000
mean     9.024064   13.018727   17.822097   36.833333
std      5.139097    2.615373   12.379710   11.726573
min      1.000000    2.000000    0.000000   18.000000
25%      5.250000   12.000000    8.000000   28.000000
50%      7.780000   12.000000   15.000000   35.000000
75%     11.250000   15.000000   26.000000   44.000000
max     44.500000   18.000000   55.000000   64.000000

In [57]:
#analysing the missing values
df1.isnull()

,wage,education,experience,age,ethnicity,region,gender,occupation,sector,union,married
rownames,,,,,,,,,,,
1,False,False,False,False,False,False,False,False,False,False,False
1100,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
529,False,False,False,False,False,False,False,False,False,False,False
530,False,False,False,False,False,False,False,False,False,False,False
531,False,False,False,False,False,False,False,False,False,False,False
532,False,False,False,False,False,False,False,False,False,False,False
533,False,False,False,False,False,False,False,False,False,False,False

In [58]:
df1.isnull().sum()

wage          0
education     0
experience    0
age           0
ethnicity     0
region        0
gender        0
occupation    0
sector        0
union         0
married       0
dtype: int64

In [60]:
#Understand categorical variables
df1["gender"].value_counts()

gender
male      289
female    245
Name: count, dtype: int64

In [61]:
df1["education"].value_counts()

education
12    219
16     71
14     56
13     37
18     31
11     27
17     24
10     17
8      15
15     13
9      12
7       5
6       3
5       1
3       1
4       1
2       1
Name: count, dtype: int64

In [62]:
type(df1)

pandas.core.frame.DataFrame

In [63]:
df1[%whos].type()

SyntaxError: invalid syntax (1762327000.py, line 1)